# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-25 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighbourhood', to='neighbourhood.Neighbourhood'),
        ),
    ]
