# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-25 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0006_auto_20210725_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='neighbourhood.Neighbourhood'),
        ),
    ]
