# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-26 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0012_auto_20210726_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
