# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-26 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0014_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='username',
            new_name='user',
        ),
    ]
